- name: Send your script to the target host
  copy: src='{{role_path}}/script/do_stuff.sh' dest=/tmp/do_stuff.sh

- name: Execute my script on target host
  command: >
          /bin/bash /tmp/do_stuff.sh
  register: output

- name: Clean up the target host by removing script
  file: path=/tmp/do_stuff.sh state=absent

- name: Print output
  debug: var=output
